spring.application.name=tech-store
spring.main.web-application-type=none
app.demo.enabled=true
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

logging.charset.console=UTF-8

app.console.enabled=true
spring.main.banner-mode=off
logging.level.root=WARN
logging.level.com.example.techstore.service.ParallelPriceService=INFO
